import React, { Component, useState } from 'react';
import $ from 'jquery';
import { Redirect, useHistory } from 'react-router-dom';

function UploadFormStep4(props) {
    $(function () {
        $('.checkbox_Style1_Label').on('click', function () {
            $(this).parent().find('.checkbox_Style1_Input').prop('checked', true);
            $(this).toggleClass('checkboxActive');
        })
    })
    return (
        <div id="divUploadForm_Step1" className="uploadForm">
            <div id="divStepExplanation" className="stepExplainContainer">
                <h1>
                    Treat these documents and passkeys as proof of ownership for this media.
                </h1>
                <p>
                    Let me tell you why. Its because you have initiated a smart contract. This multimedia file is now blockchain certified, the DMCT is a unique non fungible token generated by the blockchain to designate ownership and property. The following information are the unique keys and information required to access and track this media files blockchain tokens. 
                </p>
            </div>
            <div id="divFormStep_4" className="uploadFormInputContainer">
                <div className="uploadFormInput">
                    <label>Certificate Identification # </label>
                    <input id="mediaCID" name="mediaCID" type="text" />
                </div>
                <div className="uploadFormInput">
                    <label>Asset Identification #</label>
                    <input id="mediaAID" name="mediaAID" />
                </div>
                <div className="uploadFormInput">
                    <label>IPFS Gateway URL</label>
                    <input id="mediaIPFSURL" name="mediaIPFSURL" />
                </div>
                <div className="uploadFormInput">
                    <label>Transaction Hash (input this into Ethereum to verify Transaction and Metadata).</label>
                    <input id="mediaEtherTransactionHash" name="mediaEtherTransactionHash" />
                </div>
                <div className="checkbox_Style1">
                    <input type="checkbox" id="storeOptionRecCheck" className="checkbox_Style1_Input" />
                    <label htmlFor="storeOptionRecCheck" className="checkbox_Style1_Label">Save this information on Portfolio servers? </label>
                    <p>This means we will save the above passkeys on our servers, allowing us to track ownership and media metadata. However this also means, that if there is a security breach within our servers, you may be subject to property theft. </p>
                </div>
                <div className="checkbox_Style1">
                    <input type="checkbox" id="box-2" className="checkbox_Style1_Input" />
                    <label htmlFor="box-2" className="checkbox_Style1_Label">Store these passkeys and documents locally by myself.</label>
                    <p>This means it is completely your responsibility to ensure the safety and confidentiality of the following passkeys.</p>
                </div>
            </div>
        </div>
    );
}
export default UploadFormStep4;